name: 'OpenTofu CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  opentofu:
    name: 'OpenTofu Pipeline'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Manual Trivy Installation
        run: |
          # Adjust this URL if you need a specific version/platform
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.71.0

      - name: Setup OpenTofu
        uses: https://www.forgejo.kkulich.dev/actions/setup-opentofu@v2
        with:
          tofu_version: 1.6.0
          token: ${{ secrets.ACTIONS_TOKEN }}
      
      - name: Setup Tofu Variables
        run: |
          cat <<EOF > ./terraform/secrets.auto.tfvars
          discord_ping_webhook = "{{ secrets.TF_VAR_DISCORD_PING_WEBHOOK }}"
          discord_docker_webhook = "{{ secrets.TF_VAR_DISCORD_DOCKER_WEBHOOK }}"
          discord_postgres_webhook = "{{ secrets.TF_VAR_DISCORD_POSTGRES_WEBHOOK }}"
          discord_traefik_webhook = "{{ secrets.TF_VAR_DISCORD_TRAEFIK_WEBHOOK }}"
          uptime_kuma_username = "{{ secrets.TF_VAR_UPTIME_KUMA_USERNAME }}"
          uptime_kuma_password = "{{ secrets.TF_VAR_UPTIME_KUMA_PASSWORD }}"
          forgejo_database_hostname = "{{ secrets.TF_VAR_FORGEJO_DATABASE_HOSTNAME }}"
          forgejo_database_user = "{{ secrets.TF_VAR_FORGEJO_DATABASE_USER }}"
          forgejo_database_password = "{{ secrets.TF_VAR_FORGEJO_DATABASE_PASSWORD }}"
          immich_database_hostname = "{{ secrets.TF_VAR_IMMICH_DATABASE_HOSTNAME }}"
          immich_database_user = "{{ secrets.TF_VAR_IMMICH_DATABASE_USER }}"
          immich_database_password = "{{ secrets.TF_VAR_IMMICH_DATABASE_PASSWORD }}"
          EOF

      - name: Tofu Format
        run: tofu fmt -check

      - name: Tofu Init
        run: tofu init
        working-directory: ./terraform

      - name: Tofu Validate
        run: tofu validate
        working-directory: ./terraform

      #- name: Tofu Security Scan
       # uses: https://www.forgejo.kkulich.dev/actions/trivy-action@v0.36.0
        #with:
         # token: ${{ secrets.ACTIONS_TOKEN }}
          #skip-setup-trivy: true

      - name: Tofu Plan
        run: |
          tofu plan -no-color
        working-directory: ./terraform

      - name: Add Plan Comment
        if: github.event_name == 'pull_request'
        uses: https://www.forgejo.kkulich.dev/actions/github-script@v9
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const output = `#### OpenTofu Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`hcl
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Tofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve $TF_FLAGS
        working-directory: ./terraform
      - name: Cleanup Secrets
        if: always()
        run: rm -f ./terraform/secrets.auto.tfvars
