global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
  format: json
  filepath: /var/log/traefik/traefik.log
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    entryPoint: metrics
accessLog:
  filepath: /var/log/traefik/access.log
  format: json
  filters:
    statusCodes:
      - '200'
      - '400-499'
      - '500-503'
  fields:
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Content-Type: keep
api:
  dashboard: true
  insecure: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    observability:
      accessLogs: false
      metrics: false
      tracing: false
  websecure:
    address: :443
  metrics:
    address: ":9090"
certificatesResolvers:
  cloudflare:
    acme:
      email: 'klpv733@gmail.com'
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: proxy
