services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    container_name: forgejo
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    memswap_limit: -1
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__actions__ENABLED=true
      - FORGEJO__admin__DISABLE_REGULAR_ORG_CREATION=true
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=forgejo_db:5432
      - FORGEJO__database__NAME=${POSTGRES_DB}
      - FORGEJO__database__USER=${POSTGRES_USER}
      - FORGEJO__database__PASSWD=${POSTGRES_PASSWORD}
      - FORGEJO__repository__ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT=false
      - FORGEJO__repository__MAX_CREATION_LIMIT=0
      - FORGEJO__service__DISABLE_REGISTRATION=true
    restart: always
    labels:
      traefik.enable: true
      traefik.docker.network: forgejo_traefik
      traefik.http.routers.forgejo.entrypoints: websecure
      traefik.http.routers.forgejo.tls: true
      traefik.http.routers.forgejo.tls.certresolver: cloudflare
      traefik.http.routers.forgejo.tls.domains[0].main: www.forgejo.kkulich.dev
      traefik.http.routers.forgejo.tls.domains[0].sans: forgejo.kkulich.dev
      traefik.http.routers.forgejo.rule: Host(`forgejo.kkulich.dev`) || Host(`www.forgejo.kkulich.dev`)
      traefik.http.routers.forgejo.service: forgejo_service
      traefik.http.services.forgejo_service.loadbalancer.server.scheme: http
      traefik.http.services.forgejo_service.loadbalancer.server.port: 3000
    networks:
      - forgejo_traefik
      - forgejo_internal
    volumes:
      - /mnt/user/appdata/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:3000"
      - "222:22"
    depends_on:
      - forgejo_db
  forgejo_db:
    image: postgres:18
    restart: always
    container_name: forgejo_postgres
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 2G
          cpus: '1.0'
    memswap_limit: -1
    env_file:
      - .env
    networks:
      - forgejo_internal
      - uptime_postgres_network
    volumes:
      - /mnt/user/appdata/forgejo/postgres/:/var/lib/postgresql
networks:
  forgejo_traefik:
    external: false
    name: forgejo_traefik
  forgejo_internal:
    external: false
    name: forgejo_internal
  uptime_postgres_network:
    external: true
