services:
  server:
    image: codeberg.org/forgejo/forgejo:15
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.forejo.entrypoints: websecure
      traefik.http.routers.forejo.tls: true
      traefik.http.routers.forejo.tls.certresolver: cloudflare
      traefik.http.routers.forejo.tls.domains[0].main: www.forejo.kkulich.dev
      traefik.http.routers.forejo.tls.domains[0].sans: forejo.kkulich.dev
      traefik.http.routers.forejo.rule: Host(`forejo.kkulich.dev`) || Host(`www.forejo.kkulich.dev`)
      traefik.http.routers.forejo.service: forejo_service
      traefik.http.services.forejo_service.loadbalancer.server.scheme: http
      traefik.http.services.forejo_service.loadbalancer.server.port: 4000
    networks:
      - forejo_traefik
    volumes:
      - /mnt/user/appdata/forejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:3000"
      - "222:22"
networks:
  forejo_traefik:
    external: false
    name: forejo_traefik
