name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    hostname: homepage.kkulich.dev
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 256M
          cpus: '0.25'
    memswap_limit: -1
    networks:
      - homepage_traefik
    ports:
      - 3000:3000
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.tls.certresolver: cloudflare
      traefik.http.routers.homepage.tls.domains[0].main: www.homepage.kkulich.dev
      traefik.http.routers.homepage.tls.domains[0].sans: homepage.kkulich.dev
      traefik.http.routers.homepage.rule: Host(`homepage.kkulich.dev`) || Host(`www.homepage.kkulich.dev`)
      traefik.http.routers.homepage.service: homepage_service
      traefik.http.services.homepage_service.loadbalancer.server.scheme: http
      traefik.http.services.homepage_service.loadbalancer.server.port: 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/app/config
    # Environment settings
    env_file: .env
    environment:
      PUID: $PUID
      PGID: $PGID
networks:
  homepage_traefik:
    name: homepage_traefik
    driver: bridge
    external: false
    enable_ipv6: false
    attachable: false
