services:
  # The Docker-in-Docker service
  docker-in-docker:
    image: docker:dind
    container_name: forgejo-dind
    privileged: true
    restart: unless-stopped
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    environment:
      DOCKER_TLS_CERTDIR: ""

  # The Forgejo Runner
  runner:
    image: data.forgejo.org/forgejo/runner:12
    links:
      - docker-in-docker
    container_name: forgejo-runner
    restart: unless-stopped
    depends_on:
      docker-in-docker:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    volumes:
      - /mnt/user/appdata/forgejo-runners/data:/data
      #- /mnt/user/appdata/forgejo-runners/config.yaml:/config.yaml
    user: 1001:1001
    command: 'forgejo-runner daemon --config runner-config.yml'
