---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    labels:
      traefik.enable: true
      traefik.http.routers.vscode.entrypoints: websecure
      traefik.http.routers.vscode.tls: true
      traefik.http.routers.vscode.tls.certresolver: cloudflare
      traefik.http.routers.vscode.rule: Host(`code.kkulich.dev`) || Host(`www.code.kkulich.dev`)
      traefik.http.routers.vscode.tls.domains[0].main: www.code.kkulich.dev
      traefik.http.routers.vscode.tls.domains[0].sans: code.kkulich.dev
      traefik.http.routers.vscode.server: vscode_service
      traefik.http.services.vscode_service.loadbalancer.server.scheme: http
      traefik.http.services.vscode_service.loadbalancer.server.port: 8443
    networks:
      - code:internal
      - code:traefik
    ports:
      - 9500:8443
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/vscode/config:/config
    env_file:
      - .env
networks:
  "code:internal":
    name: "code:internal"
    driver: bridge
    external: true
    enable_ipv6: false
    attachable: false
  "code:traefik":
    name: "authentik:traefik"
    driver: bridge
    external: true
    attachable: true
